# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebc95714280a7142ab83532937f0f8454447f6aaa55fb3877896fe74cad5e287dace643d26dced181f2be1f429091ee78eab2caf92a66959c0afbf5fca73a1db

test:
  secret_key_base: d86ce653ea6d4141fab57707c836464936c11806439f58fb9a42686acf45ea3f4ee1a6016dfed93c6cb070ffccbe603a65cda24fc8ae193f302f8373c384d0f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
